// Analytic answers complement the standard-Julia oracle. Property fixtures return
// scaled residuals or orthogonality defects; zero then has a meaningful tolerance.
export const cases = [
  { name: 'columns', expected: [0, 0], concept: 'matrix columns, slices, functions, loops' },
  { name: 'composition', expected: [1, 3, 0], concept: 'composition and transformed origin' },
  { name: 'dependence', expected: [0, 0, 0], concept: 'nullspace and nonunique coefficients' },
  { name: 'square', expected: [1.4, 1.2], concept: 'square solve' },
  { name: 'square-pivot', expected: [2, -1, 3, 0], concept: 'pivoting and reconstruction' },
  { name: 'square-matrix-rhs', expected: [1, -2, 3, 4, 2, 2, 0], concept: 'square solve with two right-hand sides' },
  { name: 'square-small-scale', expected: [1, -2, 0], concept: 'scale-aware square solve below 1e-14' },
  { name: 'square-large-scale', expected: [1, -2, 0], concept: 'scale-aware square solve above 1e14' },
  { name: 'projection', expected: [2, 1, 0], concept: 'projection and orthogonal residual' },
  { name: 'projection-function', expected: [2, 1, 0, 0], concept: 'projection implemented as learner function' },
  { name: 'projection-zero', error: 'zero direction', concept: 'explicit zero-direction guard' },
  { name: 'least-squares', expected: [7 / 6, 1 / 2], concept: 'direct rectangular least squares' },
  { name: 'least-squares-properties', expected: [7 / 6, 1 / 2, 0, 1 / 6], concept: 'nonzero residual with column-space orthogonality' },
  { name: 'least-squares-matrix-rhs', expected: [7 / 6, 1 / 2, 2, -1, 2, 2, 0], concept: 'rectangular solve with two right-hand sides' },
  { name: 'least-squares-near-dependent', expected: [2, -1, 0], atol: 1e-6, concept: 'near dependence without normal equations' },
  { name: 'least-squares-small-scale', expected: [7 / 6, 1 / 2, 0], concept: 'small-scale rectangular solve' },
  { name: 'least-squares-large-scale', expected: [7 / 6, 1 / 2, 0], concept: 'large-scale rectangular solve' },
  { name: 'least-squares-rank-deficient', expected: [0.6, 1.2, 0, 0], concept: 'rank-deficient minimum-norm least squares' },
  { name: 'wide-minimum-norm', expected: [1 / 3, 4 / 3, 5 / 3, 0, 0], concept: 'underdetermined minimum-norm solve' },
  { name: 'conditioning', expected: [1e-6, 1, 0, 2], concept: 'small residual versus solution error' },
  { name: 'conditioning-sweep', expected: [1, 1, 1], concept: 'functions and loops over sensitivity examples' },
  { name: 'learner-function-solves', expected: [7 / 6, 7 / 6, 7 / 6, 1 / 2, 1 / 2, 1 / 2, 0.6, 0.6, 0.6, 1.2, 1.2, 1.2, 1 / 3, 1 / 3, 1 / 3, 4 / 3, 4 / 3, 4 / 3, 5 / 3, 5 / 3, 5 / 3], shape: [3, 7], concept: 'learner function and loop: tall, rank-deficient, and wide solves at three scales' },
  { name: 'qr-least-squares', expected: [7 / 6, 1 / 2], concept: 'explicit QR calculation' },
  { name: 'broadcast', expected: [5, 11, 1, 4], concept: 'matrix multiply versus elementwise multiply' },
  { name: 'array-language', expected: [7, 10, 0, 1, 2, 3], concept: 'mutation, ranges, broadcasting, transpose, array dimensions' },
  { name: 'dimension-error', error: 'dimension|size', concept: 'matrix multiply dimension diagnostic' },
  { name: 'solve-dimension-error', error: 'dimension|size|length|rows', concept: 'square solve RHS dimension diagnostic' },
  { name: 'least-squares-dimension-error', error: 'dimension|size|length|rows', concept: 'rectangular solve RHS dimension diagnostic' },
  { name: 'singular', error: 'singular', concept: 'singular square solve diagnostic' },
];

